# Generated by Django 2.1.5 on 2019-07-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiracloud', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
