# Generated by Django 2.1.5 on 2019-09-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiracloud', '0007_profile_remote_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storypoint_name_field',
            field=models.CharField(default='customfield_10027', max_length=32),
            preserve_default=False,
        ),
    ]
