# Generated by Django 2.1.5 on 2019-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_contact_jira_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='jira_username',
            field=models.CharField(max_length=254),
        ),
    ]
